// flow-typed signature: f07a72ca0d88b496690e9619f25ba007
// flow-typed version: <<STUB>>/ba64_v^3.0.9/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ba64'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ba64' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'ba64/index' {
  declare module.exports: $Exports<'ba64'>;
}
declare module 'ba64/index.js' {
  declare module.exports: $Exports<'ba64'>;
}
