// flow-typed signature: 869502375020db5d364fc24c89e2d0a7
// flow-typed version: <<STUB>>/bootstrap-css-only_v^4.3.1/flow_v0.112.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bootstrap-css-only'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bootstrap-css-only' {
  declare module.exports: any;
}
