// flow-typed signature: 9a91a72cdbf32a1b554168d057a87d34
// flow-typed version: <<STUB>>/eslint-config-erb_v^0.1.1/flow_v0.112.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-erb'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-erb' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'eslint-config-erb/index' {
  declare module.exports: $Exports<'eslint-config-erb'>;
}
declare module 'eslint-config-erb/index.js' {
  declare module.exports: $Exports<'eslint-config-erb'>;
}
