// flow-typed signature: f10c1477671b73026d17626a1ed9bb3c
// flow-typed version: <<STUB>>/eslint-plugin-compat_v^3.3.0/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-compat'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-compat' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-compat/lib/config/recommended' {
  declare module.exports: any;
}

declare module 'eslint-plugin-compat/lib/constants' {
  declare module.exports: any;
}

declare module 'eslint-plugin-compat/lib/helpers' {
  declare module.exports: any;
}

declare module 'eslint-plugin-compat/lib' {
  declare module.exports: any;
}

declare module 'eslint-plugin-compat/lib/providers/caniuse-provider' {
  declare module.exports: any;
}

declare module 'eslint-plugin-compat/lib/providers' {
  declare module.exports: any;
}

declare module 'eslint-plugin-compat/lib/providers/mdn-provider' {
  declare module.exports: any;
}

declare module 'eslint-plugin-compat/lib/rules/compat' {
  declare module.exports: any;
}

declare module 'eslint-plugin-compat/lib/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-compat/lib/config/recommended.js' {
  declare module.exports: $Exports<'eslint-plugin-compat/lib/config/recommended'>;
}
declare module 'eslint-plugin-compat/lib/constants.js' {
  declare module.exports: $Exports<'eslint-plugin-compat/lib/constants'>;
}
declare module 'eslint-plugin-compat/lib/helpers.js' {
  declare module.exports: $Exports<'eslint-plugin-compat/lib/helpers'>;
}
declare module 'eslint-plugin-compat/lib/index' {
  declare module.exports: $Exports<'eslint-plugin-compat/lib'>;
}
declare module 'eslint-plugin-compat/lib/index.js' {
  declare module.exports: $Exports<'eslint-plugin-compat/lib'>;
}
declare module 'eslint-plugin-compat/lib/providers/caniuse-provider.js' {
  declare module.exports: $Exports<'eslint-plugin-compat/lib/providers/caniuse-provider'>;
}
declare module 'eslint-plugin-compat/lib/providers/index' {
  declare module.exports: $Exports<'eslint-plugin-compat/lib/providers'>;
}
declare module 'eslint-plugin-compat/lib/providers/index.js' {
  declare module.exports: $Exports<'eslint-plugin-compat/lib/providers'>;
}
declare module 'eslint-plugin-compat/lib/providers/mdn-provider.js' {
  declare module.exports: $Exports<'eslint-plugin-compat/lib/providers/mdn-provider'>;
}
declare module 'eslint-plugin-compat/lib/rules/compat.js' {
  declare module.exports: $Exports<'eslint-plugin-compat/lib/rules/compat'>;
}
declare module 'eslint-plugin-compat/lib/types.js' {
  declare module.exports: $Exports<'eslint-plugin-compat/lib/types'>;
}
