// flow-typed signature: 5873619de6c7789bb3e0f6b9a6ca67ab
// flow-typed version: <<STUB>>/react-tab-view_v^1.1.1/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-tab-view'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-tab-view' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-tab-view/example' {
  declare module.exports: any;
}

declare module 'react-tab-view/example/webpack.config' {
  declare module.exports: any;
}

declare module 'react-tab-view/lib/__tests__/tab.spec' {
  declare module.exports: any;
}

declare module 'react-tab-view/lib' {
  declare module.exports: any;
}

declare module 'react-tab-view/lib/Tab' {
  declare module.exports: any;
}

declare module 'react-tab-view/lib/Tabs' {
  declare module.exports: any;
}

declare module 'react-tab-view/src/__tests__/tab.spec' {
  declare module.exports: any;
}

declare module 'react-tab-view/src' {
  declare module.exports: any;
}

declare module 'react-tab-view/src/tab' {
  declare module.exports: any;
}

declare module 'react-tab-view/src/tabs' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-tab-view/example/index' {
  declare module.exports: $Exports<'react-tab-view/example'>;
}
declare module 'react-tab-view/example/index.js' {
  declare module.exports: $Exports<'react-tab-view/example'>;
}
declare module 'react-tab-view/example/webpack.config.js' {
  declare module.exports: $Exports<'react-tab-view/example/webpack.config'>;
}
declare module 'react-tab-view/lib/__tests__/tab.spec.js' {
  declare module.exports: $Exports<'react-tab-view/lib/__tests__/tab.spec'>;
}
declare module 'react-tab-view/lib/index' {
  declare module.exports: $Exports<'react-tab-view/lib'>;
}
declare module 'react-tab-view/lib/index.js' {
  declare module.exports: $Exports<'react-tab-view/lib'>;
}
declare module 'react-tab-view/lib/Tab.js' {
  declare module.exports: $Exports<'react-tab-view/lib/Tab'>;
}
declare module 'react-tab-view/lib/Tabs.js' {
  declare module.exports: $Exports<'react-tab-view/lib/Tabs'>;
}
declare module 'react-tab-view/src/__tests__/tab.spec.js' {
  declare module.exports: $Exports<'react-tab-view/src/__tests__/tab.spec'>;
}
declare module 'react-tab-view/src/index' {
  declare module.exports: $Exports<'react-tab-view/src'>;
}
declare module 'react-tab-view/src/index.js' {
  declare module.exports: $Exports<'react-tab-view/src'>;
}
declare module 'react-tab-view/src/tab.js' {
  declare module.exports: $Exports<'react-tab-view/src/tab'>;
}
declare module 'react-tab-view/src/tabs.js' {
  declare module.exports: $Exports<'react-tab-view/src/tabs'>;
}
