// flow-typed signature: 0f1648a1b25d54ca4aa49d8a12c869e7
// flow-typed version: <<STUB>>/react-router-tabs_v^1.3.2/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-router-tabs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-router-tabs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-router-tabs/cjs/react-router-tabs' {
  declare module.exports: any;
}

declare module 'react-router-tabs/cjs/react-router-tabs.min' {
  declare module.exports: any;
}

declare module 'react-router-tabs/esm/react-router-tabs' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-router-tabs/cjs/react-router-tabs.js' {
  declare module.exports: $Exports<'react-router-tabs/cjs/react-router-tabs'>;
}
declare module 'react-router-tabs/cjs/react-router-tabs.min.js' {
  declare module.exports: $Exports<'react-router-tabs/cjs/react-router-tabs.min'>;
}
declare module 'react-router-tabs/esm/react-router-tabs.js' {
  declare module.exports: $Exports<'react-router-tabs/esm/react-router-tabs'>;
}
declare module 'react-router-tabs/index' {
  declare module.exports: $Exports<'react-router-tabs'>;
}
declare module 'react-router-tabs/index.js' {
  declare module.exports: $Exports<'react-router-tabs'>;
}
