// flow-typed signature: f97d13a78505cdce58d2d851786e5208
// flow-typed version: <<STUB>>/react-slideshow-image_v^1.3.3/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-slideshow-image'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-slideshow-image' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-slideshow-image/dist/app.bundle' {
  declare module.exports: any;
}

declare module 'react-slideshow-image/dist/react-slideshow-image.min' {
  declare module.exports: any;
}

declare module 'react-slideshow-image/lib/components/slideshow/fade' {
  declare module.exports: any;
}

declare module 'react-slideshow-image/lib/components/slideshow/slide' {
  declare module.exports: any;
}

declare module 'react-slideshow-image/lib/components/slideshow/zoom' {
  declare module.exports: any;
}

declare module 'react-slideshow-image/lib/helpers' {
  declare module.exports: any;
}

declare module 'react-slideshow-image/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-slideshow-image/dist/app.bundle.js' {
  declare module.exports: $Exports<'react-slideshow-image/dist/app.bundle'>;
}
declare module 'react-slideshow-image/dist/react-slideshow-image.min.js' {
  declare module.exports: $Exports<'react-slideshow-image/dist/react-slideshow-image.min'>;
}
declare module 'react-slideshow-image/lib/components/slideshow/fade.js' {
  declare module.exports: $Exports<'react-slideshow-image/lib/components/slideshow/fade'>;
}
declare module 'react-slideshow-image/lib/components/slideshow/slide.js' {
  declare module.exports: $Exports<'react-slideshow-image/lib/components/slideshow/slide'>;
}
declare module 'react-slideshow-image/lib/components/slideshow/zoom.js' {
  declare module.exports: $Exports<'react-slideshow-image/lib/components/slideshow/zoom'>;
}
declare module 'react-slideshow-image/lib/helpers.js' {
  declare module.exports: $Exports<'react-slideshow-image/lib/helpers'>;
}
declare module 'react-slideshow-image/lib/index' {
  declare module.exports: $Exports<'react-slideshow-image/lib'>;
}
declare module 'react-slideshow-image/lib/index.js' {
  declare module.exports: $Exports<'react-slideshow-image/lib'>;
}
