// flow-typed signature: f36c8fda8ff7591e3974736e15e3b892
// flow-typed version: <<STUB>>/react-quiz-component_v^0.3.7/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-quiz-component'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-quiz-component' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-quiz-component/lib/Answer' {
  declare module.exports: any;
}

declare module 'react-quiz-component/lib/core-components/Explanation' {
  declare module.exports: any;
}

declare module 'react-quiz-component/lib/core-components/helpers' {
  declare module.exports: any;
}

declare module 'react-quiz-component/lib/core-components/InstantFeedback' {
  declare module.exports: any;
}

declare module 'react-quiz-component/lib/core-components/QuizResultFilter' {
  declare module.exports: any;
}

declare module 'react-quiz-component/lib/Core' {
  declare module.exports: any;
}

declare module 'react-quiz-component/lib/Core' {
  declare module.exports: any;
}

declare module 'react-quiz-component/lib/Locale' {
  declare module.exports: any;
}

declare module 'react-quiz-component/lib/Locale' {
  declare module.exports: any;
}

declare module 'react-quiz-component/lib/Question' {
  declare module.exports: any;
}

declare module 'react-quiz-component/lib/Question' {
  declare module.exports: any;
}

declare module 'react-quiz-component/lib/Quiz' {
  declare module.exports: any;
}

declare module 'react-quiz-component/lib/Quiz' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-quiz-component/lib/Answer.js' {
  declare module.exports: $Exports<'react-quiz-component/lib/Answer'>;
}
declare module 'react-quiz-component/lib/core-components/Explanation.js' {
  declare module.exports: $Exports<'react-quiz-component/lib/core-components/Explanation'>;
}
declare module 'react-quiz-component/lib/core-components/helpers.js' {
  declare module.exports: $Exports<'react-quiz-component/lib/core-components/helpers'>;
}
declare module 'react-quiz-component/lib/core-components/InstantFeedback.js' {
  declare module.exports: $Exports<'react-quiz-component/lib/core-components/InstantFeedback'>;
}
declare module 'react-quiz-component/lib/core-components/QuizResultFilter.js' {
  declare module.exports: $Exports<'react-quiz-component/lib/core-components/QuizResultFilter'>;
}
declare module 'react-quiz-component/lib/Core.js' {
  declare module.exports: $Exports<'react-quiz-component/lib/Core'>;
}
declare module 'react-quiz-component/lib/Core.jsx' {
  declare module.exports: $Exports<'react-quiz-component/lib/Core'>;
}
declare module 'react-quiz-component/lib/Locale.js' {
  declare module.exports: $Exports<'react-quiz-component/lib/Locale'>;
}
declare module 'react-quiz-component/lib/Locale.jsx' {
  declare module.exports: $Exports<'react-quiz-component/lib/Locale'>;
}
declare module 'react-quiz-component/lib/Question.js' {
  declare module.exports: $Exports<'react-quiz-component/lib/Question'>;
}
declare module 'react-quiz-component/lib/Question.jsx' {
  declare module.exports: $Exports<'react-quiz-component/lib/Question'>;
}
declare module 'react-quiz-component/lib/Quiz.js' {
  declare module.exports: $Exports<'react-quiz-component/lib/Quiz'>;
}
declare module 'react-quiz-component/lib/Quiz.jsx' {
  declare module.exports: $Exports<'react-quiz-component/lib/Quiz'>;
}
