// flow-typed signature: b9e3db4ccfb148278ad3e6ad4ceac069
// flow-typed version: <<STUB>>/react-slideshow-image_v^2.0.1/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-slideshow-image'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-slideshow-image' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-slideshow-image/dist/react-slideshow-image.min' {
  declare module.exports: any;
}

declare module 'react-slideshow-image/lib/fade' {
  declare module.exports: any;
}

declare module 'react-slideshow-image/lib/helpers' {
  declare module.exports: any;
}

declare module 'react-slideshow-image/lib' {
  declare module.exports: any;
}

declare module 'react-slideshow-image/lib/slide' {
  declare module.exports: any;
}

declare module 'react-slideshow-image/lib/zoom' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-slideshow-image/dist/react-slideshow-image.min.js' {
  declare module.exports: $Exports<'react-slideshow-image/dist/react-slideshow-image.min'>;
}
declare module 'react-slideshow-image/lib/fade.js' {
  declare module.exports: $Exports<'react-slideshow-image/lib/fade'>;
}
declare module 'react-slideshow-image/lib/helpers.js' {
  declare module.exports: $Exports<'react-slideshow-image/lib/helpers'>;
}
declare module 'react-slideshow-image/lib/index' {
  declare module.exports: $Exports<'react-slideshow-image/lib'>;
}
declare module 'react-slideshow-image/lib/index.js' {
  declare module.exports: $Exports<'react-slideshow-image/lib'>;
}
declare module 'react-slideshow-image/lib/slide.js' {
  declare module.exports: $Exports<'react-slideshow-image/lib/slide'>;
}
declare module 'react-slideshow-image/lib/zoom.js' {
  declare module.exports: $Exports<'react-slideshow-image/lib/zoom'>;
}
