// flow-typed signature: 8ce9175a59f37e088abd5219db26aca3
// flow-typed version: <<STUB>>/reactjs-popup_v^1.5.0/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'reactjs-popup'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'reactjs-popup' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'reactjs-popup/reactjs-popup.cjs' {
  declare module.exports: any;
}

declare module 'reactjs-popup/reactjs-popup.es' {
  declare module.exports: any;
}

declare module 'reactjs-popup/reactjs-popup' {
  declare module.exports: any;
}

declare module 'reactjs-popup/reactjs-popup.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'reactjs-popup/reactjs-popup.cjs.js' {
  declare module.exports: $Exports<'reactjs-popup/reactjs-popup.cjs'>;
}
declare module 'reactjs-popup/reactjs-popup.es.js' {
  declare module.exports: $Exports<'reactjs-popup/reactjs-popup.es'>;
}
declare module 'reactjs-popup/reactjs-popup.js' {
  declare module.exports: $Exports<'reactjs-popup/reactjs-popup'>;
}
declare module 'reactjs-popup/reactjs-popup.min.js' {
  declare module.exports: $Exports<'reactjs-popup/reactjs-popup.min'>;
}
